export const FETCH_VOCAB_SUCCESS = "FETCH_VOCAB_SUCCESS";
export const FETCH_VOCAB_FAILED = "FETCH_VOCAB_FAILED";
export const FETCH_VOCAB_LOADING = "FETCH_VOCAB_LOADING";

export const START_FLASHCARD = "START_FLASHCARD";
export const END_FLASHCARD = "END_FLASHCARD";
